app:
  name: "FreshAgentLab"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8000

agents:
  num_ideas: 2
  max_loops: 3
  validation_threshold: 0.7

models:
  default_provider: "anthropic"
  anthropic_model: "claude-3-5-sonnet-20241022"
  openai_model: "gpt-4"

memory:
  session_timeout: 3600  # 1 hour
  max_sessions: 100